---
- name: Edit UAB Idp metadata file to replace OrganizationName value to UAB Central Authentication System
  become: yes
  replace:
    path: /etc/xdmod/simplesamlphp/metadata/saml20-idp-remote.php
    regexp: "('OrganizationName' =>\\s*array \\(\\s*'en' =>\\s*')University of Alabama at Birmingham(',\\s*\\))"
    replace: "\\1UAB Central Authentication System\\2"

- name: Copy UAB logo to /gui/images
  template:
    src: logo.png
    dest: /gui/images/uab-logo.png

- name: Edit UAB idp metadata to add uab-logo
  ansible.builtin.replace:
    path: /etc/xdmod/simplesamlphp/metadata/saml20-idp-remote.php 
    regexp: "(array \\(\\s*0 => 'uab\\.edu',\\s*\\),)"
    replace: "\\1\n    'icon' => '/etc/xdmod/simplesamlphp/uab-logo.png',"

