---
- name: Install PHP and required modules
  yum:
    name:
      - php
      - php-mbstring
      - php-xml
      - mod_php
    state: latest

- name: Extract SimpleSAMLphp
  unarchive:
    src: "{{ simplesaml_url }}"
    dest: /var/www/
    remote_src: true
    extra_opts: [--strip-components=1]
  become: true

- name: Create config, metadata, and cert directories for SimpleSAMLPHP
  become: yes
  file:
    path: /etc/xdmod/simplesamlphp/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - config
    - metadata
    - cert

- name: Install python3 and pip3
  yum:
    name:
      - python3
      - python3-pip

- name: Install require package
  pip:
    name: boto3
    extra_args: "--extra-index-url https://pypi.python.org/simple"
    executable: "/usr/bin/pip3"

- name: create a shib directory in /tmp
  file:
    path: "/tmp/{{ lookup('env', 's3_shibboleth_bucket_name') }}"
    state: directory

- name: Adding a debug step to print out the LTS env variables
  ansible.builtin.debug:
    msg:
    - "s3_endpoint: {{ lookup('env', 's3_endpoint') }}"
    - "s3_shibboleth_bucket_name: {{ lookup('env', 's3_shibboleth_bucket_name') }}"
    - "s3_shibboleth_object_name: {{ lookup('env', 's3_shibboleth_object_name') }}"

- name: Download shibboleth tar from S3
  aws_s3:
    mode: get
    s3_url: "{{ lookup('env', 's3_endpoint') }}"
    bucket: "{{ lookup('env', 's3_shibboleth_bucket_name') }}"
    object: "{{ lookup('env', 's3_shibboleth_object_name') }}"
    dest: "/tmp/{{ lookup('env', 's3_shibboleth_object_name') }}"
    aws_access_key: "{{ lookup('env', 'lts_access_key') }}"
    aws_secret_key: "{{ lookup('env', 'lts_secret_key') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Extract tar.gz into /tmp/
  unarchive:
    src: "/tmp/{{ lookup('env', 's3_shibboleth_object_name') }}"
    dest: "/tmp/{{ lookup('env', 's3_shibboleth_bucket_name') }}"
    remote_src: yes

- name: Copy all the cert and metadata files to appropriate destinations
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: "/tmp/{{ lookup('env', 's3_shibboleth_bucket_name') }}/key.pem", dest: "/etc/xdmod/simplesamlphp/cert/key.pem" }
    - { src: "/tmp/{{ lookup('env', 's3_shibboleth_bucket_name') }}/cert.pem", dest: "/etc/xdmod/simplesamlphp/cert/cert.pem" }
    - { src: "/tmp/{{ lookup('env', 's3_shibboleth_bucket_name') }}/authsources.php", dest: "/etc/xdmod/simplesamlphp/config/authsources.php" }
    - { src: "/tmp/{{ lookup('env', 's3_shibboleth_bucket_name') }}/saml20-idp-remote.php", dest: "/etc/xdmod/simplesamlphp/metadata/saml20-idp-remote.php" }

- name: Copy config file from templates to destination
  template:
    src: config.php
    dest: /etc/xdmod/simplesamlphp/config/config.php
    mode: 0644

- name: Add [authentication] section to portal_settings.ini
  blockinfile:
    path: /etc/xdmod/portal_settings.ini
    block: |
      [authentication]
      source = "default-sp"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - DO NOT EDIT"
    insertafter: '^basic_auth = "on"$'

- name: Create log directory
  file:
    path: "/var/log/simplesaml"
    state: directory
    mode: '0775'
    owner: apache
    group: apache

- name: Create log file
  file:
    path: "/var/log/simplesaml/simplesamlphp.log"
    state: touch
    mode: '0664'
    owner: apache
    group: apache

- name: Restart httpd service
  become: true
  systemd:
    name: httpd.service
    state: restarted

