---
- name: Install PHP and required modules
  yum:
    name:
      - php
      - php-mbstring
      - php-xml
      - mod_php
    state: latest

- name: Download SimpleSAMLphp to /tmp dir
  get_url:
    url: https://github.com/simplesamlphp/simplesamlphp/releases/download/v1.19.7/simplesamlphp-1.19.7.tar.gz
    dest: /tmp/simplesamlphp/
    mode: '0755'

- name: Extract SimpleSAMLphp
  unarchive:
    src: /tmp/simplesamlphp/simplesamlphp-1.19.7.tar.gz
    dest: /var/www/
    remote_src: true

- name: Create config, metadata, and cert directories for SimpleSAMLPHP
  become: yes
  file:
    path: /etc/xdmod/simplesamlphp/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - config
    - metadata
    - cert

- name: Copy all the cert and metadata files to appropriate destinations
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: "saml.pem", dest: "/etc/xdmod/simplesamlphp/cert/saml.pem" }
    - { src: "saml.crt", dest: "/etc/xdmod/simplesamlphp/cert/saml.crt" }
    - { src: "authsources.php", dest: "/etc/xdmod/simplesamlphp/config/authsources.php" }
    - { src: "saml20-idp-remote.php", dest: "/etc/xdmod/simplesamlphp/metadata/saml20-idp-remote.php" }

- name: Copy config file from templates to destination
  template:
    src: config.php
    dest: /etc/xdmod/simplesamlphp/config/config.php

- name: Create log file
  file:
    path: "/var/log/simplesaml/simplesamlphp.log"
    state: touch
    mode: '0664'
    owner: apache
    group: apache

- name: Restart httpd service
  become: true
  systemd:
    name: httpd.service
    state: restarted

