---
- name: Edit UAB Idp metadata file to replace OrganizationName value to UAB Central Authentication System
  become: yes
  replace:
    path: /etc/xdmod/simplesamlphp/metadata/saml20-idp-remote.php
    regexp: "('OrganizationDisplayName' =>\\s*array \\(\\s*'en' =>\\s*')University of Alabama at Birmingham(',\\s*\\))"
    replace: "\\1UAB Central Authentication System\\2"

- name: Copy UAB logo to /gui/images
  copy:
    src: logo.png
    dest: /usr/share/xdmod/html/gui/images/uab-logo.png 

- name: Edit UAB idp metadata to add uab-logo
  ansible.builtin.replace:
    path: /etc/xdmod/simplesamlphp/metadata/saml20-idp-remote.php 
    regexp: "(array \\(\\s*0 => 'uab\\.edu',\\s*\\),)"
    replace: "\\1\n    'icon' => '/gui/images/uab-logo.png',"

- name: Install python3 and pip3
  yum:
    name:
      - python3
      - python3-pip

- name: Install require package
  pip:
    name: boto3
    extra_args: "--extra-index-url https://pypi.python.org/simple"
    executable: "/usr/bin/pip3"

- name: create a cert directory in /tmp
  file:
    path: "/tmp/cert"
    state: directory

- name: Adding a debug step to print out the LTS env variables
  ansible.builtin.debug:
    msg:
    - "s3_endpoint: {{ lookup('env', 's3_endpoint') }}"
    - "s3_shibboleth_bucket_name: {{ lookup('env', 's3_shibboleth_bucket_name') }}"
    - "s3_shibboleth_object_name: {{ lookup('env', 's3_cert_object_name') }}"

- name: Download cert tar from S3
  aws_s3:
    mode: get
    s3_url: "{{ lookup('env', 's3_endpoint') }}"
    bucket: "{{ lookup('env', 's3_shibboleth_bucket_name') }}"
    object: "{{ lookup('env', 's3_cert_object_name') }}"
    dest: "/tmp/{{ lookup('env', 's3_cert_object_name') }}"
    aws_access_key: "{{ lookup('env', 'lts_access_key') }}"
    aws_secret_key: "{{ lookup('env', 'lts_secret_key') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Extract tar.gz into /tmp/cert
  unarchive:
    src: "/tmp/{{ lookup('env', 's3_cert_object_name') }}"
    dest: "/tmp/cert"
    remote_src: yes

- name: Copy all the cert and key files to appropriate destinations
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: "/tmp/cert/xdmod.rc.uab.edu-2048-incommon-cert.crt", dest: "/etc/pki/tls/certs/xdmod.rc.uab.edu-2048-incommon-cert.crt" }
    - { src: "/tmp/cert/xdmod.rc.uab.edu-2048-incommon-interm.crt", dest: "/etc/pki/tls/certs/xdmod.rc.uab.edu-2048-incommon-interm.crt" }
    - { src: "/tmp/cert/xdmod.rc.uab.edu-2048.key", dest: "/etc/pki/tls/private/xdmod.rc.uab.edu-2048.key" }

- name: Replace the apache config values for cert
  become: yes
  replace:
    path: /etc/httpd/conf.d/xdmod.conf
    regexp: '(SSLCertificateFile ).*'
    replace: "    SSLCertificateFile /etc/pki/tls/certs/xdmod.rc.uab.edu-2048-incommon-cert.crt"

- name: Replace the apache config values for key
  become: yes
  replace:
    path: /etc/httpd/conf.d/xdmod.conf
    regexp: '(SSLCertificateKeyFile ).*'
    replace: "    SSLCertificateKeyFile /etc/pki/tls/private/xdmod.rc.uab.edu-2048.key"

- name: Add config for interm cert
  become: yes
  lineinfile:
    path: /etc/httpd/conf.d/xdmod.conf
    insertafter: '(SSLCertificateKeyFile ).*'
    line: '    SSLCertificateChainFile /etc/ssl/certs/xdmod.rc.uab.edu-2048-incommon-interm.crt'
    state: present

- name: Replace constant in constants.php
  become: yes
  replace:
    path: /usr/share/xdmod/configuration/constants.php
    regexp: "(define\\('RESTRICTION_USERNAME[^{]*{)\\d(.*)$"
    replace: "\\1 {{xdmod_min_username_length}}\\2"
    backup: true

- name: Restart httpd service
  become: true
  systemd:
    name: httpd.service
    state: restarted
  

